name: 合并节目

on:
  schedule:
    - cron: '45 4 * * *'
  workflow_dispatch:

jobs:
  merge-channels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run precise channel merger
      run: |
        python hebing.py 2>&1 | tee merge_log.txt
        if grep -q "未找到匹配源" merge_log.txt; then
          echo "::warning::Some channels not found in sources"
          grep "未找到匹配源" merge_log.txt
        fi
      shell: bash
      
    - name: Commit changes
      if: success() && github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add txt/live.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Precise channel update [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}