name: IP Address Update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    # 首先检出当前仓库（包含zbip.py）
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    # 然后检出私有仓库
    - name: Checkout private repository
      uses: actions/checkout@v4
      with:
        repository: 168xb/zubo
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        path: private-repo
        fetch-depth: 0
        
    - name: Verify files exist
      run: |
        echo "当前目录内容:"
        ls -la
        echo "py目录内容:"
        ls -la py/
        if [ ! -f "py/zbip.py" ]; then
          echo "错误：zbip.py文件不存在"
          exit 1
        fi
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - run: pip install requests
        
    - name: Run script and update file
      run: |
        # 确保目标文件存在且是普通文件
        mkdir -p private-repo
        touch private-repo/tv
        
        # 执行脚本并写入文件
        python py/zbip.py > private-repo/tv
        echo "文件内容已更新:"
        cat private-repo/tv
        
    - name: Commit and push changes
      working-directory: private-repo
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global --add safe.directory /github/workspace/private-repo
        
        if [ -n "$(git status --porcelain)" ]; then
          echo "检测到文件变更，准备提交..."
          git add tv
          git commit -m "自动更新: $(date +'%Y-%m-%d %H:%M:%S')"
          git pull --rebase
          git push
          echo "变更已成功推送"
        else
          echo "没有文件变更，跳过提交"
        fi