name: Auto Sync Zubo Files

on:
  push:
    branches:
      - main  # 指定你的分支名
    paths:
      - 'vv/zubo_*.txt'   # 严格路径匹配
      - 'vv/zubo_*.txt'  # 双重匹配确保触发
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    permissions: write-all  # 确保完整权限
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.LIVELIST }}
        fetch-depth: 0  # 获取完整历史
        ref: ${{ github.ref }}  # 明确指定引用

    - name: Debug file changes
      run: |
        echo "触发分支: ${{ github.ref }}"
        echo "所有变化文件:"
        git diff --name-only HEAD^ HEAD
        echo "匹配文件:"
        git diff --name-only HEAD^ HEAD -- 'vv/zubo_*.txt'

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone private repository
      run: |
        git clone https://${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/168xb/zubo.git private-repo
      env:
        GIT_ASKPASS: echo

    - name: Copy files
      run: |
        mkdir -p private-repo/lv
        echo "复制文件列表:"
        ls vv/zubo_*.txt || echo "无匹配文件"
        cp vv/zubo_*.txt private-repo/lv/ || echo "复制完成"
        
        # 记录复制结果供后续使用
        echo "COPIED_FILES=$(ls vv/zubo_*.txt | wc -l)" >> $GITHUB_ENV

    - name: Commit to private repo
      if: env.COPIED_FILES != '0'
      run: |
        cd private-repo
        git add lv/
        git commit -m "自动同步文件 from ${{ github.repository }}"
        git push origin main

    - name: Remove original files
      if: env.COPIED_FILES != '0'
      run: |
        # 删除并提交
        rm -v vv/zubo_*.txt
        git add vv/
        git commit -m "Delete synced files"
        git push