name: Sync Zubo Files to Private Repo

on:
  push:
    paths:
      - 'vv/zubo_*.txt'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone private repository
      run: |
        git clone https://${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/168xb/zubo.git private-repo
      env:
        GIT_ASKPASS: echo

    - name: Copy files to private repo
      run: |
        # Create target directory if not exists
        mkdir -p private-repo/lv
        # Copy all matching files
        cp vv/zubo_*.txt private-repo/lv/ || echo "No zubo files to copy"
        # List copied files for logging
        echo "Copied files:"
        ls -la private-repo/lv/

    - name: Commit and push to private repo
      run: |
        cd private-repo
        git add lv/
        if git diff-index --quiet HEAD --; then
          echo "No changes to push"
        else
          git commit -m "Auto-sync zubo files from $GITHUB_REPOSITORY (${{ github.event_name == 'workflow_dispatch' && format('Manual run: {0}', inputs.reason) || 'Auto-triggered' }})"
          git push origin main
        fi

    - name: Remove original files
      run: |
        # Only remove if files were actually copied
        if [ -n "$(ls private-repo/lv/zubo_*.txt 2>/dev/null)" ]; then
          rm -f vv/zubo_*.txt
          git add vv/
          git commit -m "Remove synced zubo files" || echo "No files to remove"
          git push
        else
          echo "No zubo files found to remove"
        fi